### ISSUE TITLE
Adding on Open Source license to the project

### ISSUE THREAD

**Issue by bjedrzejewski** [maciejczyzewski/neural-chessboard#6]
This is an amazing project and I think many people would like to reuse parts of the code (if permitted) in their own personal projects. They would probably even want to use the result in larger projects (for example with RaspberryPI camera).

Would you be so kind and add an Open Source license (like MIT) to the project, or make it clear that you don't endorse such use? Thank you very much either way!

**Comment by maciejczyzewski** [comment]
Solved in https://github.com/maciejczyzewski/neural-chessboard/commit/c0770c66b8473717516b922dd6a4a3b11d31a857.
